import type { Metadata } from 'next';

import Script from 'next/script';
import './globals.css';

import ConditionalLayout from '@/app/components/ConditionalLayout';

export const metadata: Metadata = {
  title: 'TWTW Games & Animations',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 dark:bg-gray-800">
        <ConditionalLayout>{children}</ConditionalLayout>
        <Script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></Script>
      </body>
    </html>
  );
}
