name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  e2e:
    runs-on: ubuntu-latest
    needs: test # ensures unit tests run before e2e

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          browser: chrome
